/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: ['./index.html', './src/**/*.{js,jsx,ts,tsx,html}'],
    theme: {
        extend: {
            colors: {
                'primary-fixed': '#a3f69c',
                'surface-container': '#ebefe5',
                'on-error': '#ffffff',
                'on-primary-fixed': '#002204',
                'on-secondary-fixed': '#002105',
                'secondary-fixed-dim': '#83da85',
                'on-background': '#181d17',
                'primary-fixed-dim': '#88d982',
                outline: '#707a6c',
                'error-container': '#ffdad6',
                'on-tertiary': '#ffffff',
                'tertiary-fixed-dim': '#ffb1c7',
                'surface-container-high': '#e5eadf',
                'on-secondary-fixed-variant': '#005318',
                'inverse-primary': '#88d982',
                'on-error-container': '#93000a',
                'secondary-fixed': '#9ff79f',
                'on-surface': '#181d17',
                'surface-container-low': '#f1f5eb',
                'surface-container-highest': '#e0e4da',
                'inverse-on-surface': '#eef2e8',
                'outline-variant': '#bfcaba',
                background: '#f7fbf0',
                surface: '#f7fbf0',
                'on-secondary-container': '#19722b',
                primary: '#0d631b',
                error: '#ba1a1a',
                'on-primary-fixed-variant': '#005312',
                'primary-container': '#2e7d32',
                'on-primary': '#ffffff',
                'surface-dim': '#d7dbd2',
                'tertiary-fixed': '#ffd9e2',
                'on-secondary': '#ffffff',
                'on-surface-variant': '#40493d',
                'surface-tint': '#1b6d24',
                'tertiary-container': '#b14b6f',
                'surface-variant': '#e0e4da',
                'surface-container-lowest': '#ffffff',
                'inverse-surface': '#2d322b',
                tertiary: '#923357',
                'on-tertiary-fixed-variant': '#7f2448',
                'surface-bright': '#f7fbf0',
                'secondary-container': '#9cf49c',
                secondary: '#126d27',
                'on-tertiary-container': '#ffedf0',
                'on-tertiary-fixed': '#3f001c',
                'on-primary-container': '#cbffc2',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                gutter: '1.5rem',
                'container-max': '1280px',
                'stack-gap': '1rem',
                'section-py-desktop': '6rem',
                'section-py-mobile': '4rem',
            },
            fontFamily: {
                h1: ['Work Sans'],
                h2: ['Work Sans'],
                'body-md': ['Public Sans'],
                h3: ['Work Sans'],
                'body-lg': ['Public Sans'],
                label: ['Public Sans'],
            },
            fontSize: {
                h1: [
                    '60px',
                    {
                        lineHeight: '1.1',
                        letterSpacing: '-0.02em',
                        fontWeight: '700',
                    },
                ],
                h2: [
                    '36px',
                    {
                        lineHeight: '1.2',
                        letterSpacing: '-0.01em',
                        fontWeight: '700',
                    },
                ],
                'body-md': [
                    '16px',
                    {
                        lineHeight: '1.6',
                        fontWeight: '400',
                    },
                ],
                h3: [
                    '24px',
                    {
                        lineHeight: '1.3',
                        fontWeight: '600',
                    },
                ],
                'body-lg': [
                    '18px',
                    {
                        lineHeight: '1.6',
                        fontWeight: '400',
                    },
                ],
                label: [
                    '14px',
                    {
                        lineHeight: '1.4',
                        fontWeight: '600',
                    },
                ],
            },
        },
    },
    plugins: [],
}